### ISSUE TITLE
Unable to Update Campaign Tracking Code 

### ISSUE THREAD

**Issue by chelseatj3** [dolead/pytaboola#12]
I followed along with the Campaign CRUD section of the README:
```
service.get('my-campaign-id', **{'tracking_code': 'query_params'})
```
But I'm receiving the error `TypeError: get() got an unexpected keyword argument 'tracking_code'`.
I'm able to use the command without the attribute without any problems
```
service.get('my-campaign-id')
```

**Comment by chelseatj3** [comment]
Never mind, the README has an error in it, it should be update not get.

**Comment by jaesivsm** [comment]
Thanks for the report ! I'll check that out :)
