### ISSUE TITLE
build_uri in CampaignItemService

### ISSUE THREAD

**Issue by kovacicek** [dolead/pytaboola#4]
https://github.com/dolead/pytaboola/blob/2b7009db2782cfd888b85d62627cc7f27349a3a5/pytaboola/services/service.py#L37

self.account_id and self.campaign_id needs to be switched

**Comment by jaesivsm** [comment]
Hi, thanks for the report, I think this has been fixed a while ago but not really pushed to pypi. Should be fixed now. Don't hesitate to re-open if you encounter that issue again.
